echo Sync TestReReco...
rsync -r --exclude submission_scripts/crab/input_crab --exclude submission_scripts/crab/output_crab ../../additional_rereco/TestReReco/ TestReReco
echo Sync MakeTree...
rsync -r ../../additional_rereco/MakeTree/ MakeTree
echo Sync EvtGeneration...
rsync -r ../../additional_rereco/EvtGeneration/ EvtGeneration
echo Sync RawTests...
rsync -r ../../additional_rereco/RawTests/ RawTests
echo ...done

